{% set name = "colored" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4daf9b3ed687a01d59005e1bd03f354475226b933abb9a01836d6dde926d4c6f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - colored

about:
  home: https://gitlab.com/dslackw/colored
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple library for color and formatting to terminal

extra:
  recipe-maintainers:
    - ozcan
    - jan-janssen
